### ISSUE TITLE
Hammerhead upstream uneven backlight.

### ISSUE THREAD

**Issue by pparent76** [flto/linux#1]
Hi,

this is not an issue, rather a question.

When you made some tests with nexus 5 did you have the same uneven backlight problem that we currently have in postmarketOS? (the bottom-left corner is very dark) I see that you set: LM3630A_LEDB_DISABLE by default while in postmarketOS kernel we have LM3630A_LEDB_ENABLE . Can you explain why you did this, and does it have an impact on uneven backlight?

https://github.com/flto/linux/commit/72bbd453848b5aaf73b471106494ffa9064196e1

Thank's a lot in advance for your help, which I will use to try and tackle this backlight issue in postmarketOS.

**Comment by flto** [comment]
Hi,

I turned it off because I thought the backlight had only one LED, however that was wrong. You probably want to keep the lowering the default brightness part of the patch (lowering it equally for both LEDs) since the default brightness is maximum and drains battery. 

I'm not sure about the postmarketOS situation but AFAIK they are maintaining a mainline kernel+patches that works on hammerhead, and that patch is not included.

**Comment by pparent76** [comment]
Thank's a lot for your answer!

Ok we do not have a problem with draining the battery since the brightness is handled by plasma-mobile, can be changed by the user, and is lowered when there is inactivity.

But when you tested, did you notice some parts of the screen being darker than others, as we notice with postmarketOS? (See for example https://wiki.postmarketos.org/wiki/File:Small_photo_of_nexus_5.jpeg, the bottom-left hand corner is darker, white appears grey).

**Comment by flto** [comment]
If both LEDs are set to the same brightness values then that shouldn't happen. Perhaps plasma-mobile is only controlling one LED?

**Comment by pparent76** [comment]
Thanks a lot for your precious help. It may be that. Is there a way to check that, change backlight value from userspace? The two don't seem to either give me info on the current value nor change backlight value:

/sys/class/leds/mmc0\:\:/brightness
/sys/class/leds/mmc1\:\:/brightness

**Comment by flto** [comment]
I don't remember the exact sysfs path but it is something like:

`
/sys/class/backlight/lm3630/led_a/brightness
`
`
/sys/class/backlight/lm3630/led_b/brightness
`

**Comment by pparent76** [comment]
Ok I only have this existing

/sys/class/backlight/lm3630a_leda
/sys/class/backlight/backlight/

Therefore I will need to investigate. Maybe your patch disabling ledb was applied to the kernel afterall.

**Comment by flto** [comment]
It seems the patch was applied as you should have a lm3630a_ledb.

**Comment by pparent76** [comment]
Although it does not seem to be there on pmOS kernel repo:

https://gitlab.com/postmarketOS/linux-postmarketos/blob/master/drivers/video/backlight/lm3630a_bl.c

I will investigate to see if some patches may be applied on top of it.
Thank's a lot, I think I will be able to solve the problem thank's to you!

**Comment by pparent76** [comment]
This is now solved in postmarketOS: https://gitlab.com/postmarketOS/pmaports/merge_requests/33

Thank's a lot for your help it was very usefull.
