### ISSUE TITLE
Hammerhead: kernel is not allways booting ( boot race issue ).

### ISSUE THREAD

**Issue by pparent76** [flto/linux#2]
Hi,

On postmarketOS the kernel is not always booting on Nexus 5: sometimes it boots and sometimes not (then you have to restart the device again for a new attempt). I'm going to build a serial cable to investigate more.

In the mean time I just wanted to know if you had noticed this with your kernel and if you possibly had some useful information (as you had for backlight) in an attempt to solve this problem?

Thank's a lot!

**Comment by flto** [comment]
By not booting do you mean that the bootloader screen stays up and no USB device appears?

i remember some drivers might have issues with different loading orders (OCMEM driver?) but IIRC it always booted enough to get USB / display. I have workarounds for OCMEM and USB in my patches, possibly they aren't in the postmarketOS kernel?

**Comment by pparent76** [comment]
>By not booting do you mean that the bootloader screen stays up and no USB device appears?

Thank's a lot for your answer!

No google logo does not stay up, we get a blinking cursor forever. Most of the time when that happens no USB network appears on the connected computer (I did not check dmesg yet to see USB at lower level), but it also happens from times to time that network over USB works and we get an IP, but it does not boot and no service is started (SSH or plasma-mobile or tty prompt).

> I have workarounds for OCMEM and USB in my patches, possibly they aren't in the postmarketOS kernel?

Can you point me to where this is precisely?

Thank's

**Comment by flto** [comment]
In that case you can probably see what is happening in the fbcon. USB related: [this was the patch for USB](https://gist.githubusercontent.com/flto/f5280fde979744f44d8fe33c5ab3a738/raw/d5682d00f5ae91c20ec3292940bc4ab91c056850/gistfile1.txt). No services started might just be a postmarketOS issue, or a kernel crash after USB is up.

FYI, I deleted the old repository, but you can still download the patches from the wiki page.

**Comment by pparent76** [comment]
Thank's a lot for these infos! I'll work on this, I keep you updated if we solve the problem!

(Sounds unlikely to be a pmOS related problem as it happens only on this device, but we never know).

**Comment by pparent76** [comment]
This problem is solved, it was not a kernel issue but an init issue!

But thank's a lot for your tips about fbcon, it saved me a lot of time building a serial cable! ;)
